# Generated by Django 6.0.3 on 2026-03-07 11:43

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='news/photos/')),
                ('text', django_ckeditor_5.fields.CKEditor5Field()),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
