# Generated by Django 6.0.3 on 2026-03-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('theatre', 'Театр'), ('music', 'Музыка'), ('other', 'Прочее')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/photos/'),
        ),
    ]
