# Generated by Django 6.0.3 on 2026-03-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_category_alter_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
