# Generated by Django 6.0.3 on 2026-03-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
    ]
