# Generated by Django 6.0.3 on 2026-03-07 11:28

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Длительность (мин.)')),
                ('age_limit', models.CharField(default='12+', max_length=10, verbose_name='Возрастное ограничение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Спектакль',
                'verbose_name_plural': 'Спектакли',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Дата и время начала')),
                ('hall', models.CharField(default='Большой зал', max_length=120, verbose_name='Зал')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена билета')),
                ('total_seats', models.PositiveIntegerField(default=120, verbose_name='Всего мест')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='theatre.play')),
            ],
            options={
                'verbose_name': 'Показ',
                'verbose_name_plural': 'Показы',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('seats', models.PositiveIntegerField(default=1, verbose_name='Количество билетов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='theatre.showtime')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
