# Generated by Django 6.0.2 on 2026-03-07 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Если оставить пусто, ничего не будет отображаться', verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='Фотография')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_slides', to='theatre.play', verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Слайд на главной',
                'verbose_name_plural': 'Слайды на главной',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('play',), name='unique_active_play_slide')],
            },
        ),
    ]
