# Generated by Django 6.0.2 on 2026-03-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_mainslide'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mainslide',
            name='unique_active_play_slide',
        ),
        migrations.DeleteModel(
            name='MainSlide',
        ),
    ]
