# Generated by Django 6.0.2 on 2026-03-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_remove_mainslide_unique_active_play_slide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeShowcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_showcase/', verbose_name='Картинка в карусели')),
                ('display_date', models.DateField(blank=True, help_text='Если указать дату, карточка покажется только в этот день. Если пусто, карточка считается общей.', null=True, verbose_name='Дата показа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_showcase_items', to='theatre.play', verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Карточка витрины на главной',
                'verbose_name_plural': 'Карточки витрины на главной',
                'ordering': ['order', 'id'],
            },
        ),
    ]
