# Generated by Django 6.0.2 on 2026-03-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_homeshowcaseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория витрины',
                'verbose_name_plural': 'Категории витрины',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='homeshowcaseitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='showcase_items', to='theatre.showcasecategory', verbose_name='Категории'),
        ),
    ]
