# Generated by Django 6.0.2 on 2026-03-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0005_showcasecategory_homeshowcaseitem_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='cast',
            field=models.TextField(blank=True, default='', verbose_name='Актерский состав'),
        ),
        migrations.AddField(
            model_name='play',
            name='director',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Режиссер'),
        ),
        migrations.AddField(
            model_name='play',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='play',
            name='premiere_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата премьеры'),
        ),
        migrations.AddField(
            model_name='play',
            name='status',
            field=models.CharField(choices=[('repertory', 'В репертуаре'), ('soon', 'Скоро'), ('archive', 'Архив')], default='repertory', max_length=20, verbose_name='Статус'),
        ),
    ]
