# Generated by Django 6.0.2 on 2026-03-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0006_play_cast_play_director_play_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='hall',
            field=models.CharField(choices=[('Большой зал', 'Большой зал'), ('Маленький зал', 'Маленький зал')], default='Большой зал', max_length=120, verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='hall',
            field=models.CharField(choices=[('Большой зал', 'Большой зал'), ('Маленький зал', 'Маленький зал')], default='Большой зал', max_length=120, verbose_name='Зал'),
        ),
    ]
