# Generated by Django 6.0.3 on 2026-03-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0008_play_poster_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcasecategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Категория спектаклей', 'verbose_name_plural': 'Категории спектаклей'},
        ),
        migrations.AddField(
            model_name='homeshowcaseitem',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на картинку'),
        ),
        migrations.AddField(
            model_name='play',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='plays', to='theatre.showcasecategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='play',
            name='cast',
            field=models.TextField(blank=True, default='', verbose_name='Труппа'),
        ),
        migrations.AlterField(
            model_name='play',
            name='director',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Режиссер (устаревшее)'),
        ),
        migrations.AlterField(
            model_name='play',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Жанр (устаревшее)'),
        ),
        migrations.AlterField(
            model_name='play',
            name='poster_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на постер'),
        ),
        migrations.AlterField(
            model_name='play',
            name='status',
            field=models.CharField(choices=[('repertory', 'В репертуаре'), ('soon', 'Скоро'), ('archive', 'Архив')], default='repertory', max_length=20, verbose_name='Статус (устаревшее)'),
        ),
    ]
