# Generated by Django 6.0.3 on 2026-03-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='performances/posters/')),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Длительность в минутах')),
                ('age_limit', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=255)),
                ('cast', models.TextField()),
                ('premiere_date', models.DateField()),
                ('status', models.CharField(choices=[('repertoire', 'В репертуаре'), ('soon', 'Скоро'), ('archive', 'Архив')], default='repertoire', max_length=20)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
